[package]
name = "backbeat_server"
version = "0.5.1"
edition.workspace = true
authors = ["zkldi <zkldi@proton.me>"]
readme = "README.md"
license = "GPL-3.0"
description = "The reference backbeat server implementation."
repository = "https://github.com/zkldi/backbeat"

[dependencies]
backbeat_core = { workspace = true }
backbeat_sdk = { workspace = true }
backbeat_store_config = { workspace = true }

axum = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["io"] }
thiserror = { workspace = true }
tracing = { workspace = true }
mime_guess = { workspace = true }

[dev-dependencies]
tempfile.workspace = true
serde_json = { workspace = true }
tower = { workspace = true, features = ["util"] }
tokio = { workspace = true }
backbeat_core = { workspace = true }
backbeat_sdk = { workspace = true, features = ["test-util"] }
