[package]
name = "backbeat_packager"
version = "0.5.1"
edition.workspace = true
description = "Package up rhythm game charts into backbeat files."
authors = ["zkldi <zkldi@proton.me>"]
readme = "README.md"
license = "GPL-3.0"
repository = "https://github.com/zkldi/backbeat"

[dependencies]
backbeat_core = { workspace = true }
backbeat_inspector = { workspace = true }
regex = { workspace = true }

rg_formats = { workspace = true }
encoding_rs = { workspace = true }

thiserror = { workspace = true }
sha2 = { workspace = true }
walkdir = { workspace = true }
moka = { workspace = true }
dashmap.workspace = true
lexical.workspace = true
image.workspace = true

[dev-dependencies]
tempfile = { workspace = true }
