[package]
name = "zk-backbeat-packager"
version = "0.1.0"
edition.workspace = true
authors = ["zkldi <zkldi@proton.me>"]
description = "zk's desktop packager for converting rhythm game charts into Backbeat archives"
license = "GPL-3.0"
repository = "https://github.com/zkldi/backbeat"

[[bin]]
name = "zk-backbeat-packager"
path = "src/main.rs"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
backbeat_core.workspace = true
backbeat_packager.workspace = true
backbeat_sdk.workspace = true
backbeat_store_config.workspace = true
open.workspace = true
serde.workspace = true
tauri.workspace = true
tauri-plugin-dialog.workspace = true
tempfile.workspace = true
walkdir.workspace = true

[lints]
workspace = true
