[package]
name = "backbeat_c_sdk"
version = "0.5.1"
edition.workspace = true
authors = ["zkldi <zkldi@proton.me>"]
description = "C SDK for Backbeat. Trivially integratable into all good games."
license = "GPL-3.0"
readme = "README.md"
keywords = ["backbeat", "rhythm-game"]
categories = []
repository = "https://github.com/zkldi/backbeat"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
backbeat_core = { workspace = true }
backbeat_server_client = { workspace = true }
backbeat_sdk = { workspace = true }
backbeat_store_config = { workspace = true }
libsqlite3-sys = "0.30.1"
futures = { workspace = true, features = ["thread-pool"] }
futures-lite = { workspace = true }
url = { workspace = true }

[build-dependencies]
cbindgen = { workspace = true }

[dev-dependencies]
backbeat_sdk = { workspace = true, features = ["test-util"] }
tempfile = { workspace = true }

[lints]
workspace = true
